### ISSUE TITLE
Error Line 61

### ISSUE THREAD

**Issue by Z3USI0TA** [lcipria/py_chd_fuse#1]
chd_fuse.py "Mickey Mania [PS1].chd" /mount/point/
  File "chd_fuse.py", line 61
    elif track := self.tracks.get(tail):
                ^
SyntaxError: invalid syntax

Please, Help me?

**Comment by Betacentury** [comment]
Hello @Z3USI0TA 

What version of python are you using?

The walrus operator (:=) requires minimum python 3.8

https://docs.python.org/3/whatsnew/3.8.html#assignment-expressions

**Comment by lcipria** [comment]
@Z3USI0TA please, can you reply?
We need to know what version of python are you using or we'll have to close this issue.
